# Numpy Practice questions beginner to advanced level

In [1]:
import numpy as np

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

array([[1, 1, 7, 8, 3, 8, 9, 7, 7, 1]])

(3, 3)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[ 0  1  2  9 10 11]
 [ 3  4  5 12 13 14]
 [ 6  7  8 15 16 17]]


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1, 16,
       -1, 18, -1, 20, -1, 22, -1, 24, -1, 26, -1, 28, -1, 30, -1, 32, -1,
       34, -1, 36, -1, 38, -1, 40, -1, 42, -1, 44, -1, 46, -1, 48, -1, 50,
       -1, 52, -1, 54, -1, 56, -1, 58, -1, 60, -1, 62, -1, 64, -1, 66, -1,
       68, -1, 70, -1, 72, -1, 74, -1, 76, -1, 78, -1, 80, -1, 82, -1, 84,
       -1, 86, -1, 88, -1, 90, -1, 92, -1, 94, -1, 96, -1, 98, -1])

array([[ 0.38368287,  0.5312532 ,  0.9739642 , -0.94445014, -1.82987214],
       [-0.94445014,  0.9739642 ,  0.82639387, -0.3541688 ,  1.41667521],
       [-1.97744248,  0.9739642 ,  0.0885422 ,  1.12153454,  0.0885422 ],
       [-0.64930947,  0.67882354,  0.0885422 , -1.68230181, -0.20659847],
       [ 1.12153454, -0.94445014,  0.82639387,  0.67882354, -1.23959081]])

array([[ 1.        , -0.73507943,  0.21226368,  0.40466252, -0.35499065],
       [-0.73507943,  1.        ,  0.31560534, -0.84163911,  0.60392191],
       [ 0.21226368,  0.31560534,  1.        , -0.21271115, -0.15159804],
       [ 0.40466252, -0.84163911, -0.21271115,  1.        , -0.68017531],
       [-0.35499065,  0.60392191, -0.15159804, -0.68017531,  1.        ]])

5.196152422706632
