# NumPy 30 Practice Questions (Beginner to Advanced)
This notebook contains 30 practice questions covering all important topics of NumPy.

## 1. Create a 1D NumPy array of numbers from 0 to 9.

In [90]:
import numpy as np

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 2. Create a 3x3 NumPy array filled with zeros.

In [4]:
np.zeros(9).reshape(3,3).astype(int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## 3. Create a 5x5 identity matrix using NumPy.

In [5]:
np.eye(5).astype(int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## 4. Create a NumPy array of 10 random floats between 0 and 1.

In [9]:
np.random.rand(10)

array([0.34581736, 0.3024294 , 0.51729291, 0.45610095, 0.0244233 ,
       0.140084  , 0.39930756, 0.60636335, 0.32298628, 0.22174503])

## 5. Create a 2D array and reshape it from 1D to 2D.

In [10]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## 6. Create a NumPy array and find its data type.

In [16]:
np.arange(25).dtype

dtype('int32')

## 7. Perform element-wise addition on two NumPy arrays.

In [23]:
arr_1 = np.arange(10).reshape(2,5)
arr_2 = np.arange(10,20).reshape(2,5)
print(arr_1+arr_2)

[[10 12 14 16 18]
 [20 22 24 26 28]]


## 8. Create a 1D array and slice the first 5 elements.

In [28]:
np.arange(10)[0:5]

array([0, 1, 2, 3, 4])

## 9. Find the maximum and minimum values in a NumPy array.

In [30]:
find_values = np.random.randint(0,100,10)
print(np.min(find_values))
print(np.max(find_values))

12
92


## 10. Use boolean indexing to filter values greater than 5 in a NumPy array.

In [36]:
find_values = np.random.randint(0,10,10)
find_values[find_values>5]

array([8, 7, 7])

## 11. Generate a 4x4 array with values from 0 to 15 and transpose it.

In [38]:
transpose_arr = np.arange(16).reshape(4,4)
np.transpose(transpose_arr)

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

## 12. Stack two arrays vertically and horizontally using NumPy.

In [42]:
arr_1 = np.arange(9).reshape(3,3)
arr_2 = np.arange(9,18).reshape(3,3)
print(np.vstack((arr_1,arr_2)))
print(np.hstack((arr_1,arr_2)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[ 0  1  2  9 10 11]
 [ 3  4  5 12 13 14]
 [ 6  7  8 15 16 17]]


## 13. Flatten a multi-dimensional NumPy array.

In [45]:
flattern_arr = np.arange(96).reshape(4,4,2,3)
flattern_arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95])

## 14. Use broadcasting to add a 1D array to each row of a 2D array.

In [46]:
bdc_arr = np.arange(3)
arr_2d = np.arange(9).reshape(3,3)
print(arr_2d + bdc_arr)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


## 15. Calculate the mean, median, and standard deviation of a NumPy array.

In [48]:
finder_values = np.random.randint(0,100,50)
print(np.mean(find_values))
print(np.median(find_values))
print(np.std(find_values))

3.9
3.5
2.6248809496813377


## 16. Create a 5x5 array with random integers and normalize the array.

In [49]:
normalize_arr = np.random.randint(0,25,25).reshape(5,5)
final_output = (normalize_arr - np.min(normalize_arr)) / (np.max(normalize_arr) - np.min(normalize_arr))
final_output

array([[0.45833333, 0.375     , 0.29166667, 0.20833333, 1.        ],
       [0.20833333, 0.125     , 0.91666667, 0.66666667, 0.875     ],
       [0.16666667, 0.54166667, 0.        , 0.83333333, 0.08333333],
       [0.95833333, 0.83333333, 0.45833333, 0.54166667, 0.20833333],
       [0.375     , 0.375     , 0.625     , 0.20833333, 0.625     ]])

## 17. Read a CSV file (numeric data) into a NumPy array.

#### You can skip this

## 18. Replace all even numbers in a NumPy array with -1.

In [55]:
sample_arr = np.random.randint(0,100,50)
sample_arr[sample_arr%2==0]=-1
sample_arr

array([15, 69, 61, -1, -1, -1, -1, -1, 33,  3, -1, 65, -1, -1, -1, -1, -1,
       75, -1, -1, 33, -1,  9, -1, 21, 47, -1, 77, -1, -1, 93, -1, 55, -1,
       11, -1, 67, -1,  9, 87, 29, -1, 77, 49, -1, 51, -1, 59, 53, -1])

## 19. Find the unique elements in a NumPy array.

In [58]:
val_arr = np.random.randint(0,10,20)
print(np.unique(val_arr))

[0 1 2 3 4 5 6 8 9]


## 20. Perform dot product on two matrices.

In [61]:
matric_1st = np.matrix(np.arange(9).reshape(3,3))
matric_2st = np.matrix(np.arange(9,18).reshape(3,3))
print(np.dot(matric_1st,matric_2st))

[[ 42  45  48]
 [150 162 174]
 [258 279 300]]


## 21. Create a custom universal function using np.vectorize().

In [68]:
def even_no_finder(a,b):
    if a%b==0:
        return 'Even number'
    else:
        return 'odd number'
sample_arr = np.vectorize(even_no_finder)
sample_arr(np.random.randint(10,30,40),2)

array(['Even number', 'odd number', 'Even number', 'Even number',
       'Even number', 'Even number', 'odd number', 'odd number',
       'Even number', 'Even number', 'odd number', 'odd number',
       'Even number', 'Even number', 'Even number', 'Even number',
       'Even number', 'Even number', 'odd number', 'odd number',
       'Even number', 'Even number', 'Even number', 'Even number',
       'Even number', 'Even number', 'Even number', 'odd number',
       'odd number', 'odd number', 'odd number', 'Even number',
       'odd number', 'Even number', 'Even number', 'Even number',
       'Even number', 'odd number', 'odd number', 'odd number'],
      dtype='<U11')

## 22. Use np.where() to replace values based on a condition.

In [73]:
where_arr = np.random.randint(0,20,30)
np.where(where_arr%2==0,where_arr**2,where_arr)

array([324, 324,  13,  19,  36,   9,   5, 144,  11,   7,  16,   9,   0,
        15,  11,  16,   4, 196,  36, 256,   4,  19,   9,  16, 100,  19,
         7, 100,  13, 144])

## 23. Sort a NumPy array by the second column.

In [79]:
sort_arr = np.random.randint(0,60,9).reshape(3,3)
sort_arr[sort_arr[:,1].argsort()]

array([[43, 11, 42],
       [ 0, 28, 54],
       [12, 47, 57]])

## 24. Compute the correlation coefficient between two arrays.

In [85]:
arr_1st = np.random.randint(0,9,9)
arr_2st = np.random.randint(9,18,9)
print(np.corrcoef(arr_1st,arr_2st))

[[ 1.         -0.40187463]
 [-0.40187463  1.        ]]


## 25. Create a structured array and access specific fields.

In [88]:
dtype = [('name', 'U10'), ('age', 'i4'), ('marks', 'f4')]
data = np.array([('Chetan', 23, 85.5), ('Kushal', 21, 90.0)], dtype=dtype)
data['name']

array(['Chetan', 'Kushal'], dtype='<U10')

## 26. Generate a 3D array and apply slicing on the third dimension.

In [96]:
arr_3d = np.arange(27).reshape(3,3,3)
arr_3d[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

## 27. Use NumPy to simulate 1000 coin tosses and count occurrences.

In [ ]:
# Your code hereimport numpy as np

# Simulate 1000 coin tosses (0 = Tails, 1 = Heads)
tosses = np.random.randint(0, 2, size=1000)

# Count occurrences
tails, heads = np.bincount(tosses)

print(f"Heads: {heads}")
print(f"Tails: {tails}")

## 28. Perform linear algebra operations like inverse and determinant.

In [113]:
arr_3d = np.random.randint(0,9,9).reshape(3,3)
arr_3d
np.linalg.det(arr_3d)
np.linalg.inv(np.matrix(arr_3d))

matrix([[-0.66666667,  0.66666667,  0.33333333],
        [ 0.55555556, -0.55555556, -0.11111111],
        [-0.37037037,  0.53703704,  0.07407407]])