# Basic Level

In [2]:
import numpy as np

Create a NumPy array of numbers from 1 to 10.

[ 1  2  3  4  5  6  7  8  9 10]


Create a 3×3 array filled with zeros.

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Create a 4×4 array filled with ones.

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


Create an array of even numbers between 0 and 50.


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

Generate an array of 20 random integers between 1 and 100.

[10 77 26 81 50 40 34 74 56  8 31 32 27  6 56 66 79  1 60 78]


Create an array and find its shape, size, and data type.

(5, 5)
25
int32


Convert a Python list [1,2,3,4,5] into a numpy array.

[1 2 3 4 5]


Create an array of 10 random floating values.

array([0.6694828 , 0.02719461, 0.35290936, 0.10678228, 0.26961484,
       0.70696192, 0.65128644, 0.5801891 , 0.08441895, 0.35733717])

Create a 1D array and convert it into 2D (reshape).

array([[80, 30, 64, 62],
       [80, 79, 11, 69],
       [ 7, 35, 25, 13],
       [64,  6, 18, 18],
       [25, 88,  2, 83]])

Create a NumPy array and find its mean, median, and standard deviation.

32.5
42.95
29.982453201831234


Create an array and find the sum of all elements.

859

Generate a 5×5 identity matrix.

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


Create an array and access the 2nd, 4th, and last element.

array([64, 80, 83])

Reverse an array without using reverse() (use slicing).

array([83,  2, 88, 25, 18, 18,  6, 64, 13, 25, 35,  7, 69, 11, 79, 80, 62,
       64, 30, 80])

Create two arrays and perform addition, subtraction, multiplication.

In [61]:
arr_1st = np.random.randint(1,10,15)
arr_2nd = np.random.randint(11,20,15)

array([20, 21, 26, 19, 18, 20, 20, 26, 17, 18, 18, 23, 18, 19, 21])

array([-14,  -9, -12, -13,  -8, -14, -10, -10,  -7, -10,  -6, -13,  -6,
        -3, -13])

array([ 51,  90, 133,  48,  65,  51,  75, 144,  60,  56,  72,  90,  72,
        88,  68])

# Intermediate Level

Create a 3×3 random matrix and find max & min values.

In [72]:
arr_random = np.random.randint(1,10,9).reshape(3,3)


8

Slice a 5×5 matrix to extract a 3×3 center part.

In [75]:
slc_arr =np.arange(25).reshape(5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

Concatenate two arrays vertically and horizontally.

In [83]:
arr = np.array([1,2,3,4,5,6])
arr2 = np.array([7,8,9,10,11,12])

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Generate an array of 25 values and reshape it to 5×5.

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

Sort a numpy array in ascending and descending order.

In [98]:
random_arr = np.random.randint(0,100,25)


array([ 2,  3,  7, 24, 26, 27, 38, 40, 42, 45, 51, 60, 67, 75, 76, 77, 80,
       81, 86, 92, 95, 95, 96, 96, 99])

array([99, 96, 96, 95, 95, 92, 86, 81, 80, 77, 76, 75, 67, 60, 51, 45, 42,
       40, 38, 27, 26, 24,  7,  3,  2])

Create an array and replace all values greater than 50 with 50.

In [134]:
sample = np.random.randint(1,100,50)


In [135]:
sample

array([50, 37, 50, 50, 41,  4, 50, 50, 50, 16, 50,  8, 50, 40, 41, 29, 50,
       50, 44, 50, 50, 50, 50, 50, 32, 50, 50, 50,  9, 50, 28, 50, 50, 20,
       50, 43, 48, 50, 36, 50, 42, 50, 50, 40, 50, 50, 50, 45, 50, 50])

Find unique elements from an array.

array([50, 37, 50, 50, 41,  4, 50, 50, 50, 16, 50,  8, 50, 40, 41, 29, 50,
       50, 44, 50, 50, 50, 50, 50, 32, 50, 50, 50,  9, 50, 28, 50, 50, 20,
       50, 43, 48, 50, 36, 50, 42, 50, 50, 40, 50, 50, 50, 45, 50, 50])

array([ 4,  8,  9, 16, 20, 28, 29, 32, 36, 37, 40, 41, 42, 43, 44, 45, 48,
       50])

Stack two arrays using vstack() and hstack().

array([[ 3,  6,  7,  3,  5,  3,  5,  8,  5,  4,  6,  5,  6,  8,  4],
       [17, 15, 19, 16, 13, 17, 15, 18, 12, 14, 12, 18, 12, 11, 17]])

array([ 3,  6,  7,  3,  5,  3,  5,  8,  5,  4,  6,  5,  6,  8,  4, 17, 15,
       19, 16, 13, 17, 15, 18, 12, 14, 12, 18, 12, 11, 17])

Create a matrix and find row-wise and column-wise sums.

matrix([[50, 55, 60, 65, 70]])

matrix([[ 10],
        [ 35],
        [ 60],
        [ 85],
        [110]])

Multiply two matrices using dot() and matmul().

In [149]:
a = np.array([1,2,3])
b = np.array([4,5,6])


32
32


Create an array from 0 to 1 with step 0.1 (arange).

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

Generate a linearly spaced array of 10 numbers between 5 and 50.

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

Create a 3D array and print its first 2 rows.

In [17]:
sampple_arr = np.random.randint(0,10,16).reshape(2,4,2)

array([[1, 4],
       [8, 6]])

Get the index of max & min elements from an array.

2
0


Replace negative numbers in an array with 0.

In [29]:
neg_arr = np.random.randn(10)

array([0.        , 0.        , 0.43634877, 0.19829392, 0.        ,
       0.        , 0.5176347 , 0.        , 0.855686  , 0.        ])

Create a boolean mask array from a normal array (e.g. find values > 30)

In [32]:
bool_arr = np.random.randint(0,100,60)


array([False, False,  True,  True,  True,  True, False, False, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True, False,  True, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True, False,  True,  True,  True,  True,
       False,  True, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

Perform element-wise square, square-root, exponential.

In [45]:
new_arr = np.random.randint(5,20,5)

[361 289 361 196 225]

[4.35889894 4.12310563 4.35889894 3.74165739 3.87298335]

[1.78482301e+08 2.41549528e+07 1.78482301e+08 1.20260428e+06
 3.26901737e+06]


Read an array and find covariance using np.cov().

In [52]:
new_arr
new_arr2 = np.array([5,7,9,10,4])

array([[ 5.2 , -0.75],
       [-0.75,  6.5 ]])

Create two arrays and compute correlation coefficient using np.corrcoef().

array([[ 1.        , -0.12900392],
       [-0.12900392,  1.        ]])

Flatten a multi-dimensional array into 1D using ravel()/flatten()

[1 4 8 6 6 3 3 7 2 1 8 6 5 7 1 5]
[1 4 8 6 6 3 3 7 2 1 8 6 5 7 1 5]


# Advanced Level

Create a random 6×6 matrix and extract the diagonal elements.

In [69]:
sample_6 = np.random.randint(0,20,36).reshape(6,6)


array([[16,  1,  0, 16,  8,  1],
       [ 4, 11,  4,  7, 15, 16],
       [ 7, 18,  9,  4, 17, 15],
       [16,  7, 15, 17, 19, 14],
       [ 1,  9, 19, 10, 16,  2],
       [15,  1,  0, 17, 10, 12]])

array([16, 11,  9, 17, 16, 12])

In [78]:
np.diag(sample_6)

array([16, 11,  9, 17, 16, 12])

Normalize a numpy array to values between 0 and 1.

In [82]:
x = np.random.rand(10)
normalize = (x-x.min())/(x.max()-x.min())

In [83]:
normalize

array([1.        , 0.91604206, 0.27999059, 0.99422452, 0.07443699,
       0.28445064, 0.        , 0.54420367, 0.7501639 , 0.64120214])

Write code to find missing values (NaN) and replace them with the mean

In [118]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80],dtype='float')
arr[2] = np.nan

In [121]:
mean_value = np.nanmean(arr)

In [125]:
np.nan_to_num(arr,nan=np.nanmean(arr)).astype(int)

array([10, 20, 47, 40, 50, 60, 70, 80])

Create a 5×5 matrix and rotate it by 90 degrees.

In [133]:
degree_arr = np.arange(0,25).reshape(5,5)
np.rot90(degree_arr)

array([[ 4,  9, 14, 19, 24],
       [ 3,  8, 13, 18, 23],
       [ 2,  7, 12, 17, 22],
       [ 1,  6, 11, 16, 21],
       [ 0,  5, 10, 15, 20]])

Perform broadcasting on two arrays of different shapes.

In [138]:
sample1 = np.arange(9).reshape(3,3)
sample2 = np.array([11,12,13]).reshape(3,1)

In [142]:
print(sample1+sample2)
print()
print(sample1*sample2)

[[11 12 13]
 [15 16 17]
 [19 20 21]]

[[  0  11  22]
 [ 36  48  60]
 [ 78  91 104]]


Create a function using numpy to calculate Euclidean distance.

In [149]:
arr1 = np.array([1,2])
arr2 = np.array([3,4])
euc_dist = np.sqrt(((arr2[0]-arr1[0])**2) +(arr2[1]-arr1[1])**2)
euc_dist

2.8284271247461903

Generate a dataset of 1000 values following a normal distribution.

In [3]:
data = np.random.normal(loc=0, scale=1, size=1000)

print(data)

[ 9.01796671e-01 -2.25002756e+00 -1.14874127e+00  3.18543615e-01
  1.70587735e+00  2.11918770e-01 -1.22305924e+00 -4.48229064e-02
  1.25566858e+00 -4.45795153e-01 -1.06534005e-01  1.20947850e+00
  1.18564056e+00  5.59998032e-01 -3.84660890e-01 -1.78058606e+00
 -1.32034594e+00  1.46824691e-02  2.13913821e-01 -3.22255491e-01
 -1.46239265e-01  7.61542343e-01  5.47215459e-01 -3.98141907e-01
  2.82550341e-01  5.09527810e-01 -5.40439819e-01  6.72315078e-01
 -6.79799849e-01 -1.08635010e+00 -2.53028252e+00  3.06864895e+00
  6.32446014e-02  2.16102436e+00 -1.05675954e+00  1.04107887e+00
 -9.18438048e-01 -5.86777091e-01  1.53875781e+00 -5.48670157e-01
 -1.60652683e-01 -1.46351333e-01 -6.23731480e-01 -6.57827233e-01
  1.07622438e+00 -5.12963528e-01  1.51183872e+00 -4.62971688e-01
 -1.67690281e+00  6.33201547e-01  5.17954300e-01 -1.34205237e-01
 -2.31212948e-01 -6.71603698e-01  1.83672196e-01  3.54635632e-01
 -1.40397943e+00  2.08572915e-01  3.87060644e-01  3.51990596e-01
  1.03318761e+00  8.20701

Create two 3×3 matrices and find matrix inverse & determinant.

In [150]:
mat_3 = np.arange(0,9).reshape(3,3)
mat_3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [151]:
np.linalg.det(mat_3)

0.0