# 🧠 NumPy Practice Questions
This notebook contains beginner to intermediate level NumPy questions to strengthen your data manipulation and array programming skills.

## ✅ Beginner Level Questions

In [1]:
# 1. Create an array of 10 zeros.

In [2]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# 2. Create an array of 10 ones and multiply all elements by 5.

In [5]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [6]:
(np.ones(10)*5).astype(int)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [7]:
# 3. Create a 1D array of numbers from 10 to 50.

In [8]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [9]:
# 4. Create a 3x3 matrix with values ranging from 0 to 8.

In [10]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
# 5. Find the shape and data type of the array: np.array([1, 2, 3.0])

In [12]:
new_arr = np.array([1,2,3.0])

In [13]:
new_arr.shape,new_arr.dtype

((3,), dtype('float64'))

In [14]:
# 6. Reverse an array (e.g., [1, 2, 3, 4, 5]) using slicing.

In [15]:
test = np.array([1, 2, 3, 4, 5])
test[::-1]

array([5, 4, 3, 2, 1])

In [16]:
# 7. Check how many non-zero elements are in [1, 0, 2, 0, 3, 4]

In [17]:
test1 = np.random.randint(0,10,4)
print(test1)
np.size(test1[test1!=0])

[5 4 7 0]


3

## ✅ Intermediate Level Questions

In [18]:
# 8. Create a 5x5 identity matrix.

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
# 9. Generate a random array of size (4, 4) with values between 0 and 1.

In [21]:
np.random.rand(16).reshape(4,4)

array([[0.72607073, 0.88729463, 0.36146074, 0.81825996],
       [0.63654028, 0.62286332, 0.50831816, 0.13909036],
       [0.72416862, 0.27902793, 0.68209565, 0.34801334],
       [0.1450504 , 0.28571162, 0.47454122, 0.94573601]])

In [22]:
# 10. Create a 6x6 matrix with values 1 to 36 and extract the 2nd row.

In [23]:
(np.arange(1,37).reshape(6,6))[1]

array([ 7,  8,  9, 10, 11, 12])

In [24]:
# 11. Replace all values greater than 10 in an array with 10.

In [25]:
new_arr = np.random.randint(1,100,5)
new_arr[new_arr>10]=10
new_arr

array([10, 10, 10,  2, 10])

In [26]:
# 12. Split the array np.arange(16).reshape(4, 4) into 4 equal sub-arrays.

In [27]:
sample_arr = np.arange(16)
np.split(sample_arr,4)

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([12, 13, 14, 15])]

In [28]:
# 13. Find the mean, standard deviation, and variance of an array.

In [29]:
test_arr = np.arange(16)

In [30]:
print(f"{np.mean(test_arr)},{np.std(test_arr)},{np.var(test_arr)}")

7.5,4.6097722286464435,21.25


In [31]:
# 14. Sort a 2D array by the second column.

In [32]:
arr = np.array([0,2,6,4,8,5]).reshape(3,2)
sorted_arr = arr[arr[:, 1].argsort()]
print(sorted_arr)

[[0 2]
 [6 4]
 [8 5]]


In [33]:
# 15. Create a boolean mask where values > 50 in an array are True.

In [34]:
arr = np.random.randint(1,100,4)
arr>50

array([False,  True,  True,  True])

## 🧠 Bonus Challenges

In [35]:
# Normalize the data (min-max scaling)

In [36]:
data = np.array([5, 10, 15, 20, 25])

# Min-Max Normalization
data_min = np.min(data)
data_max = np.max(data)

normalized_data = (data - data_min) / (data_max - data_min)
normalized_data

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [37]:
# Remove duplicate elements from a 1D array

In [38]:
new_arr = np.random.randint(0,10,15)
np.unique(new_arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Convert a list of lists into a NumPy matrix and find the dot product

In [39]:
a,b= np.split(np.arange(16).reshape(4,4),2)

In [40]:
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [41]:
b

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
np.dot(a,b.T)

array([[ 62,  86],
       [214, 302]])